services:
  - type: web
    name: energy-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: RENDER
        value: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 